name: Open GitHub.dev

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  actions: write
  contents: read

jobs:
  open-link:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Open GitHub.dev (curl)
      run: curl -L "https://cautious-robot-v6wvjwvqw5g6hvw9.github.dev/"
