name: Open GitHub.dev

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  actions: write
  contents: read

jobs:
  open-link:
    runs-on: ubuntu-latest
    timeout-minutes: 60   # runs for 1 hour, then stops (increase if needed)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Open GitHub.dev every 5s
      run: |
        while true; do
          curl -L "https://cautious-robot-v6wvjwvqw5g6hvw9.github.dev/" || true
          echo "Opened at $(date)"
          sleep 5
        done
